package leyenda.model;
// Generated 22-abr-2019 18:21:49 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Caballero generated by hbm2java
 */
@Entity
@Table(name = "caballero", catalog = "llegenda")
public class Caballero implements java.io.Serializable {

	private String nombreCaballero;
	private Princesadragon princesadragon;
	private Integer vidaCaballero;
	private Integer defensaCaballero;
	private Set<Tiene> tienes = new HashSet<Tiene>(0);

	public Caballero() {
	}

	public Caballero(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	public Caballero(String nombreCaballero, Princesadragon princesadragon, Integer vidaCaballero,
			Integer defensaCaballero, Set<Tiene> tienes) {
		this.nombreCaballero = nombreCaballero;
		this.princesadragon = princesadragon;
		this.vidaCaballero = vidaCaballero;
		this.defensaCaballero = defensaCaballero;
		this.tienes = tienes;
	}

	@Id

	@Column(name = "nombreCaballero", unique = true, nullable = false, length = 25)
	public String getNombreCaballero() {
		return this.nombreCaballero;
	}

	public void setNombreCaballero(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nombrePrincesa")
	public Princesadragon getPrincesadragon() {
		return this.princesadragon;
	}

	public void setPrincesadragon(Princesadragon princesadragon) {
		this.princesadragon = princesadragon;
	}

	@Column(name = "vidaCaballero")
	public Integer getVidaCaballero() {
		return this.vidaCaballero;
	}

	public void setVidaCaballero(Integer vidaCaballero) {
		this.vidaCaballero = vidaCaballero;
	}

	@Column(name = "defensaCaballero")
	public Integer getDefensaCaballero() {
		return this.defensaCaballero;
	}

	public void setDefensaCaballero(Integer defensaCaballero) {
		this.defensaCaballero = defensaCaballero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "caballero")
	public Set<Tiene> getTienes() {
		return this.tienes;
	}

	public void setTienes(Set<Tiene> tienes) {
		this.tienes = tienes;
	}

}
