package leyenda.model;
// Generated 22-abr-2019 18:21:49 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Espada generated by hbm2java
 */
@Entity
@Table(name = "espada", catalog = "llegenda")
public class Espada implements java.io.Serializable {

	private String nombreEspada;
	private Integer ataqueEspada;
	private Set<Tiene> tienes = new HashSet<Tiene>(0);

	public Espada() {
	}

	public Espada(String nombreEspada) {
		this.nombreEspada = nombreEspada;
	}

	public Espada(String nombreEspada, Integer ataqueEspada, Set<Tiene> tienes) {
		this.nombreEspada = nombreEspada;
		this.ataqueEspada = ataqueEspada;
		this.tienes = tienes;
	}

	@Id

	@Column(name = "nombreEspada", unique = true, nullable = false, length = 25)
	public String getNombreEspada() {
		return this.nombreEspada;
	}

	public void setNombreEspada(String nombreEspada) {
		this.nombreEspada = nombreEspada;
	}

	@Column(name = "ataqueEspada")
	public Integer getAtaqueEspada() {
		return this.ataqueEspada;
	}

	public void setAtaqueEspada(Integer ataqueEspada) {
		this.ataqueEspada = ataqueEspada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "espada")
	public Set<Tiene> getTienes() {
		return this.tienes;
	}

	public void setTienes(Set<Tiene> tienes) {
		this.tienes = tienes;
	}

}
