package leyenda.model;
// Generated 22-abr-2019 18:21:49 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rosaconjuros generated by hbm2java
 */
@Entity
@Table(name = "rosaconjuros", catalog = "llegenda")
public class Rosaconjuros implements java.io.Serializable {

	private String nombreRosa;
	private Integer cantidadConjuros;
	private Set<Princesadragon> princesadragons = new HashSet<Princesadragon>(0);

	public Rosaconjuros() {
	}

	public Rosaconjuros(String nombreRosa) {
		this.nombreRosa = nombreRosa;
	}

	public Rosaconjuros(String nombreRosa, Integer cantidadConjuros, Set<Princesadragon> princesadragons) {
		this.nombreRosa = nombreRosa;
		this.cantidadConjuros = cantidadConjuros;
		this.princesadragons = princesadragons;
	}

	@Id

	@Column(name = "nombreRosa", unique = true, nullable = false, length = 25)
	public String getNombreRosa() {
		return this.nombreRosa;
	}

	public void setNombreRosa(String nombreRosa) {
		this.nombreRosa = nombreRosa;
	}

	@Column(name = "cantidadConjuros")
	public Integer getCantidadConjuros() {
		return this.cantidadConjuros;
	}

	public void setCantidadConjuros(Integer cantidadConjuros) {
		this.cantidadConjuros = cantidadConjuros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rosaconjuros")
	public Set<Princesadragon> getPrincesadragons() {
		return this.princesadragons;
	}

	public void setPrincesadragons(Set<Princesadragon> princesadragons) {
		this.princesadragons = princesadragons;
	}

}
