package leyenda.model;
// Generated 22-abr-2019 18:21:49 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TieneId generated by hbm2java
 */
@Embeddable
public class TieneId implements java.io.Serializable {

	private String nombreCaballero;
	private String nombreEspada;

	public TieneId() {
	}

	public TieneId(String nombreCaballero, String nombreEspada) {
		this.nombreCaballero = nombreCaballero;
		this.nombreEspada = nombreEspada;
	}

	@Column(name = "nombreCaballero", nullable = false, length = 25)
	public String getNombreCaballero() {
		return this.nombreCaballero;
	}

	public void setNombreCaballero(String nombreCaballero) {
		this.nombreCaballero = nombreCaballero;
	}

	@Column(name = "nombreEspada", nullable = false, length = 25)
	public String getNombreEspada() {
		return this.nombreEspada;
	}

	public void setNombreEspada(String nombreEspada) {
		this.nombreEspada = nombreEspada;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TieneId))
			return false;
		TieneId castOther = (TieneId) other;

		return ((this.getNombreCaballero() == castOther.getNombreCaballero())
				|| (this.getNombreCaballero() != null && castOther.getNombreCaballero() != null
						&& this.getNombreCaballero().equals(castOther.getNombreCaballero())))
				&& ((this.getNombreEspada() == castOther.getNombreEspada())
						|| (this.getNombreEspada() != null && castOther.getNombreEspada() != null
								&& this.getNombreEspada().equals(castOther.getNombreEspada())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombreCaballero() == null ? 0 : this.getNombreCaballero().hashCode());
		result = 37 * result + (getNombreEspada() == null ? 0 : this.getNombreEspada().hashCode());
		return result;
	}

}
